import type { Config } from "tailwindcss";
import daisyui from "daisyui";

const financeLightTheme = {
  "finance-light": {
    "color-scheme": "light",
    primary: "#fcd535",
    "primary-content": "#181a20",
    secondary: "#2dbdb6",
    "secondary-content": "#ffffff",
    accent: "#2dbdb6",
    "accent-content": "#181a20",
    neutral: "#181a20",
    "neutral-content": "#ffffff",
    "base-100": "#ffffff",
    "base-200": "#fafafa",
    "base-300": "#f5f5f5",
    "base-content": "#181a20",
    info: "#3b82f6",
    success: "#0ecb81",
    warning: "#f0b90b",
    error: "#f6465d",
  },
};

const financeDarkTheme = {
  "finance-dark": {
    "color-scheme": "dark",
    primary: "#fcd535",
    "primary-content": "#181a20",
    secondary: "#2dbdb6",
    "secondary-content": "#181a20",
    accent: "#2dbdb6",
    "accent-content": "#181a20",
    neutral: "#eaecef",
    "neutral-content": "#181a20",
    "base-100": "#0b0e11",
    "base-200": "#1e2329",
    "base-300": "#2b3139",
    "base-content": "#eaecef",
    info: "#3b82f6",
    success: "#0ecb81",
    warning: "#f0b90b",
    error: "#f6465d",
  },
};

const config: Config = {
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "var(--color-primary)",
        "primary-active": "var(--color-primary-active)",
        "primary-disabled": "var(--color-primary-disabled)",
        ink: "var(--color-ink)",
        body: "var(--color-body)",
        "body-on-light": "var(--color-body-on-light)",
        muted: "var(--color-muted)",
        "muted-strong": "var(--color-muted-strong)",
        "hairline-on-light": "var(--color-hairline-on-light)",
        "hairline-on-dark": "var(--color-hairline-on-dark)",
        "border-strong": "var(--color-border-strong)",
        "canvas-light": "var(--color-canvas-light)",
        "canvas-dark": "var(--color-canvas-dark)",
        "surface-card-dark": "var(--color-surface-card-dark)",
        "surface-elevated-dark": "var(--color-surface-elevated-dark)",
        "surface-soft-light": "var(--color-surface-soft-light)",
        "surface-strong-light": "var(--color-surface-strong-light)",
        "on-primary": "var(--color-on-primary)",
        "on-dark": "var(--color-on-dark)",
        "trading-up": "var(--color-trading-up)",
        "trading-down": "var(--color-trading-down)",
        "accent-turquoise": "var(--color-accent-turquoise)",
        info: "var(--color-info)",
        "info-ring": "var(--color-info-ring)",
        canvas: "var(--color-canvas)",
        "surface-card": "var(--color-surface-card)",
        "surface-elevated": "var(--color-surface-elevated)",
        "surface-soft": "var(--color-surface-soft)",
        "surface-strong": "var(--color-surface-strong)",
        "text-primary": "var(--color-text-primary)",
        "text-body": "var(--color-text-body)",
        "border-hairline": "var(--color-border-hairline)",
      },
      spacing: {
        xxs: "var(--space-xxs)",
        xs: "var(--space-xs)",
        sm: "var(--space-sm)",
        md: "var(--space-md)",
        lg: "var(--space-lg)",
        xl: "var(--space-xl)",
        xxl: "var(--space-xxl)",
        section: "var(--space-section)",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        pill: "var(--radius-pill)",
      },
      fontFamily: {
        sans: ["var(--font-family-base)"],
        display: ["var(--font-family-display)"],
        numeric: ["var(--font-family-numeric)"],
      },
    },
  },
  plugins: [daisyui],
  daisyui: {
    themes: [financeLightTheme, financeDarkTheme],
    logs: false,
  },
};

export default config;
