FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    scikit-learn \
    pandas \
    psycopg2-binary \
    joblib \
    numpy \
    schedule

COPY src/ml/trainer.py .

CMD ["python", "trainer.py"]
